### Create User
POST http://localhost:8081/api/app-user
Content-Type: application/json

{
  "name": "Alice",
  "email": "Alice@hotmail.com"
}

### Get All Users
GET http://localhost:8081/api/app-user

### Get User By Name
GET http://localhost:8081/api/app-user/Test%20User2

### Start Async
GET http://localhost:8081/demo-start-async

### Wait for Async
GET http://localhost:8081/demo-wait-for-async

### Start Async2
GET http://localhost:8081/demo-start-async2

### Send First Request
GET http://localhost:8081/receive-first

### Send Second Request
GET http://localhost:8081/receive-second/HORAHORA

### Send First Request 1 (Multi Request)
GET http://localhost:8081/receive-first-request/11

### Send First Request 2 (Multi Request)
GET http://localhost:8081/receive-first-request/22

### Send Second Request 1 (Multi Request)
GET http://localhost:8081/receive-second-request/11/ARAARA

### Send Second Request 2 (Multi Request)
GET http://localhost:8081/receive-second-request/22/AHOY